# **_Linear Regression_**


## OLS (Ordinary Least Squares)


### Closed Form (Normal form)


In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

Normal form:

theta = (X.T _ X)^-1 _ X.T \* y

where X is the feature matrix and y is the target vector


In [3]:
df = pd.read_csv("./Dataset/score.csv")
df.head()

Hours  Scores
0    2.5      21
1    5.1      47
2    3.2      27
3    8.5      75
4    3.5      30

In [7]:
X = np.array(df.Hours.values)
X = np.stack(
    [
        np.ones(
            X.shape,
        ),
        X,
    ],
    axis=1,
)
X[:2]

array([[1. , 2.5],
       [1. , 5.1]])

In [13]:
X.shape

(25, 2)

In [9]:
y = df.Scores.values[:, np.newaxis]
print("Shape of Y = ", y.shape)
y[:2]

Shape of Y =  (25, 1)


array([[21],
       [47]])

In [32]:
# creation of dataset for Normal Form
def cal_theta_mat(X, y):
    theta = np.linalg.inv(np.dot(X.T, X)) @ X.T @ y
    # theta = theta @ X.T
    # theta = theta @ y

    return theta

In [21]:
def pred(m,X,c):
    y_pred = []

    for i in range(X.shape[0]):
        y_pred.append((m*X[i])+c)
    
    return y_pred

In [15]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.1, random_state=2)

y_train.shape

(22, 1)

In [16]:
X_train.shape

(22, 2)

In [23]:
X_test[0]

array([1. , 1.1])

In [24]:
def theta_calc2(x_train, y_train):
    # Initializing all variables
    n_data = x_train.shape[0]
    bias = np.ones((n_data, 1))
    x_train_b = np.append(bias, x_train, axis=1)
    #
    theta_1 = np.linalg.inv(np.dot(x_train_b.T, x_train_b))
    theta_2 = np.dot(theta_1, x_train_b.T)
    theta = np.dot(theta_2, y_train)
    #
    return theta

In [31]:
X_train[:, 1].shape

(22,)

In [30]:
theta2 = theta_calc2(X_train[:,1], y_train)

ValueError: all the input arrays must have same number of dimensions, but the array at index 0 has 2 dimension(s) and the array at index 1 has 1 dimension(s)

In [33]:
m, c = cal_theta_mat(X_train, y_train)

In [34]:
m,c

(array([2.01575521]), array([9.85520355]))

In [35]:
y_pred = pred(m=m, X=X_test, c=c)
y_pred

[array([11.87095876, 12.07253429]),
 array([11.87095876, 14.89459159]),
 array([11.87095876, 13.68513846])]

# Ridge and Lasso Regression


In [2]:
df = pd.read_csv("./Dataset/Boston.csv", index_col=0)
df

crim    zn  indus  chas    nox     rm   age     dis  rad  tax  \
1    0.00632  18.0   2.31     0  0.538  6.575  65.2  4.0900    1  296   
2    0.02731   0.0   7.07     0  0.469  6.421  78.9  4.9671    2  242   
3    0.02729   0.0   7.07     0  0.469  7.185  61.1  4.9671    2  242   
4    0.03237   0.0   2.18     0  0.458  6.998  45.8  6.0622    3  222   
5    0.06905   0.0   2.18     0  0.458  7.147  54.2  6.0622    3  222   
..       ...   ...    ...   ...    ...    ...   ...     ...  ...  ...   
502  0.06263   0.0  11.93     0  0.573  6.593  69.1  2.4786    1  273   
503  0.04527   0.0  11.93     0  0.573  6.120  76.7  2.2875    1  273   
504  0.06076   0.0  11.93     0  0.573  6.976  91.0  2.1675    1  273   
505  0.10959   0.0  11.93     0  0.573  6.794  89.3  2.3889    1  273   
506  0.04741   0.0  11.93     0  0.573  6.030  80.8  2.5050    1  273   

     ptratio   black  lstat  medv  
1       15.3  396.90   4.98  24.0  
2       17.8  396.90   9.14  21.6  
3       17.8  392.83   4.03  34.7  
4       18.7  394.63   2.94  33.4  
5       18.7  396.90   5.33  36.2  
..       ...     ...    ...   ...  
502     21.0  391.99   9.67  22.4  
503     21.0  396.90   9.08  20.6  
504     21.0  396.90   5.64  23.9  
505     21.0  393.45   6.48  22.0  
506     21.0  396.90   7.88  11.9  

[506 rows x 14 columns]

In [3]:
df.iloc[:, 0]

1      0.00632
2      0.02731
3      0.02729
4      0.03237
5      0.06905
        ...   
502    0.06263
503    0.04527
504    0.06076
505    0.10959
506    0.04741
Name: crim, Length: 506, dtype: float64